server:
  port: 8097

spring:
  application:
    name: MyCarLong

#  security:
#    user:
#      name: test@test.com
#      password: 12345

  devtools:
    restart:
      enabled: true

  livereload:
    enabled: true

  thymeleaf:
    cache: false

  datasource: # RDS 연동시 수정해야함
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myCarLong
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

#  servlet:
#    multipart:
#      maxFileSize: 20MB
#      maxRequestSize: 100MB

itemImgLocation: D:/shop/item

uploadPath: file:///D:/shop/

driver:
  chrome:

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


springdoc:
  swagger-ui:
    path: /swagger-docs
    disable-swagger-default-url: true
    display-request-duration: true




